package std.wlj.std.script;

import org.familysearch.standards.core.lang.StdUnicodeBlock;

public class PrintSampleUnicodeChar {
    
    static StdUnicodeBlock[] allBlocks = {
        StdUnicodeBlock.BLOCK_BASIC_LATIN,
        StdUnicodeBlock.BLOCK_LATIN_SUPPLEMENT,
        StdUnicodeBlock.BLOCK_LATIN_EXT_ADD,
        StdUnicodeBlock.BLOCK_LATIN_EXT_A,
        StdUnicodeBlock.BLOCK_LATIN_EXT_B,
        StdUnicodeBlock.BLOCK_LATIN_EXT_C,
        StdUnicodeBlock.BLOCK_LATIN_EXT_D,
        StdUnicodeBlock.BLOCK_LATIN_EXT_E,
        StdUnicodeBlock.BLOCK_CYRILLIC,
        StdUnicodeBlock.BLOCK_CYRILLIC_SUPPLEMENT,
        StdUnicodeBlock.BLOCK_CYRILLIC_EXT_A,
        StdUnicodeBlock.BLOCK_CYRILLIC_EXT_B,
        StdUnicodeBlock.BLOCK_CYRILLIC_EXT_C,
        StdUnicodeBlock.BLOCK_CJK_RADICALS,
        StdUnicodeBlock.BLOCK_CJK_SYMBOLS_PUNCT,
        StdUnicodeBlock.BLOCK_CJK_STROKES,
        StdUnicodeBlock.BLOCK_CJK_LETTERS_MONTHS,
        StdUnicodeBlock.BLOCK_CJK_COMPATIBILITY,
        StdUnicodeBlock.BLOCK_CJK_EXT_A,
        StdUnicodeBlock.BLOCK_CJK_EXT_B,
        StdUnicodeBlock.BLOCK_CJK_EXT_C,
        StdUnicodeBlock.BLOCK_CJK_EXT_D,
        StdUnicodeBlock.BLOCK_CJK_EXT_E,
        StdUnicodeBlock.BLOCK_CJK_COMPAT_IDEOGRAPHS_SUPPL,
        StdUnicodeBlock.BLOCK_CJK_UNIFIED_IDEOGRAPHS,
        StdUnicodeBlock.BLOCK_CJK_COMPAT_IDEOGRAPHS,
        StdUnicodeBlock.BLOCK_CJK_COMPAT_FORMS,
        StdUnicodeBlock.BLOCK_HANGUL_JAMO,
        StdUnicodeBlock.BLOCK_HANGUL_JAMO_COMPAT,
        StdUnicodeBlock.BLOCK_HANGUL_JAMO_EXT_A,
        StdUnicodeBlock.BLOCK_HANGUL_JAMO_EXT_B,
        StdUnicodeBlock.BLOCK_HANGUL_SYLLABLES,
        StdUnicodeBlock.BLOCK_ARMENIAN,
        StdUnicodeBlock.BLOCK_HEBREW,
        StdUnicodeBlock.BLOCK_ARABIC,
        StdUnicodeBlock.BLOCK_ARABIC_SUPPL,
        StdUnicodeBlock.BLOCK_ARABIC_EXT_A,
        StdUnicodeBlock.BLOCK_ARABIC_PRES_FORMS_A,
        StdUnicodeBlock.BLOCK_ARABIC_PRES_FORMS_B,
        StdUnicodeBlock.BLOCK_ARABIC_MATH_ALPHA_SYMBOLS,
        StdUnicodeBlock.BLOCK_SYRIAC,
        StdUnicodeBlock.BLOCK_THAANA,
        StdUnicodeBlock.BLOCK_SAMARITAN,
        StdUnicodeBlock.BLOCK_MANDAIC,
        StdUnicodeBlock.BLOCK_DEVANAGARI,
        StdUnicodeBlock.BLOCK_DEVANAGARI_EXT,
        StdUnicodeBlock.BLOCK_BENGALI,
        StdUnicodeBlock.BLOCK_GURMUKHI,
        StdUnicodeBlock.BLOCK_GUJARATI,
        StdUnicodeBlock.BLOCK_ORIYA,
        StdUnicodeBlock.BLOCK_TAMIL,
        StdUnicodeBlock.BLOCK_TELUGU,
        StdUnicodeBlock.BLOCK_KANNADA,
        StdUnicodeBlock.BLOCK_MALAYALAM,
        StdUnicodeBlock.BLOCK_SINHALA,
        StdUnicodeBlock.BLOCK_THAI,
        StdUnicodeBlock.BLOCK_LAO,
        StdUnicodeBlock.BLOCK_TIBETAN,
        StdUnicodeBlock.BLOCK_MYANMAR,
        StdUnicodeBlock.BLOCK_MYANMAR_EXT_A,
        StdUnicodeBlock.BLOCK_MYANMAR_EXT_B,
        StdUnicodeBlock.BLOCK_GEORGIAN,
        StdUnicodeBlock.BLOCK_GEORGIAN_SUPPL,
        StdUnicodeBlock.BLOCK_ETHIOPIC,
        StdUnicodeBlock.BLOCK_ETHIOPIC_SUPPL,
        StdUnicodeBlock.BLOCK_ETHIOPIC_EXT,
        StdUnicodeBlock.BLOCK_ETHIOPIC_EXT_A,
        StdUnicodeBlock.BLOCK_CHEROKEE,
        StdUnicodeBlock.BLOCK_CHEROKEE_SUPPL,
        StdUnicodeBlock.BLOCK_UNIFIED_CAN_ABOR_SYLL,
        StdUnicodeBlock.BLOCK_OGHAM,
        StdUnicodeBlock.BLOCK_RUNIC,
        StdUnicodeBlock.BLOCK_TAGALOG,
        StdUnicodeBlock.BLOCK_HANUNOO,
        StdUnicodeBlock.BLOCK_BUHID,
        StdUnicodeBlock.BLOCK_TAGBANWA,
        StdUnicodeBlock.BLOCK_KHMER,
        StdUnicodeBlock.BLOCK_MONGOLIAN,
        StdUnicodeBlock.BLOCK_UNIFIED_CAN_ABOR_SYLL_EXT,
        StdUnicodeBlock.BLOCK_LIMBU,
        StdUnicodeBlock.BLOCK_TAI_LE,
        StdUnicodeBlock.BLOCK_NEW_TAI_LE,
        StdUnicodeBlock.BLOCK_KHMER_SYMBOLS,
        StdUnicodeBlock.BLOCK_BUGINESE,
        StdUnicodeBlock.BLOCK_TAI_THAM,
        StdUnicodeBlock.BLOCK_COMBINING_DIAC_MARKS_EXT,
        StdUnicodeBlock.BLOCK_BALINESE,
        StdUnicodeBlock.BLOCK_SUNDANESE,
        StdUnicodeBlock.BLOCK_BATAK,
        StdUnicodeBlock.BLOCK_LEPCHA,
        StdUnicodeBlock.BLOCK_OL_CHIKI,
        StdUnicodeBlock.BLOCK_SUNDANESE_SUPPL,
        StdUnicodeBlock.BLOCK_VEDIC_EXT,
        StdUnicodeBlock.BLOCK_COPTIC,
        StdUnicodeBlock.BLOCK_KANGXI_RADICALS,
        StdUnicodeBlock.BLOCK_IDEOGRAPH_DESC_CHARS,
        StdUnicodeBlock.BLOCK_HIRAGANA,
        StdUnicodeBlock.BLOCK_KATAKANA,
        StdUnicodeBlock.BLOCK_KATAKANA_PHONETIC_EXT,
        StdUnicodeBlock.BLOCK_BOPOMOFO,
        StdUnicodeBlock.BLOCK_BOPOMOFO_EXT,
        StdUnicodeBlock.BLOCK_KANBUN,
        StdUnicodeBlock.BLOCK_YIJING_HEX_SYMBOLS,
        StdUnicodeBlock.BLOCK_YI_SYLLABLES,
        StdUnicodeBlock.BLOCK_YI_RADICALS,
        StdUnicodeBlock.BLOCK_LISU,
        StdUnicodeBlock.BLOCK_VAI,
        StdUnicodeBlock.BLOCK_HALFWIDTH_FULLWIDTH_FORMS,
        StdUnicodeBlock.BLOCK_KANA_SUPPL,
        StdUnicodeBlock.BLOCK_GREEK_COPTIC,
        StdUnicodeBlock.BLOCK_GREEK_EXT,
        StdUnicodeBlock.BLOCK_PRIVATE_USE_AREA,
        StdUnicodeBlock.BLOCK_HIGH_PRIVATE_USE_SURROGATES,
        StdUnicodeBlock.BLOCK_HIGH_SURROGATES,
        StdUnicodeBlock.BLOCK_LOW_SURROGATES,
        StdUnicodeBlock.BLOCK_SPECIALS,
        StdUnicodeBlock.BLOCK_SUPPLEMENTARY_PRIVATE_USE_A,
        StdUnicodeBlock.BLOCK_SUPPLEMENTARY_PRIVATE_USE_B,
        StdUnicodeBlock.BLOCK_BOX_DRAWING,
        StdUnicodeBlock.BLOCK_BLOCK_ELEMENTS,
        StdUnicodeBlock.BLOCK_GEOMETRIC_SHAPES,
        StdUnicodeBlock.BLOCK_MISC_SYMBOLS,
        StdUnicodeBlock.BLOCK_DINGBATS,
        new StdUnicodeBlock( "Kana Half-Full Width", 0xFF65, 0xFF9F )
    };

    public static void main(String...args) {
        for (StdUnicodeBlock block : allBlocks) {
            for (int i=0;  i<block.getBlocks().size();  i++) {
                int start = block.getBlocks().get(i).getStart();
                System.out.println(block.getName() + " >>" + (char)start + " " + (char)(start+1) + " " + (char)(start+2) + "<<");
            }
        }
    }
}
